### PR TITLE
Make work with Python 3

### PR DESCRIPTION
**Pull request by scop**
Briefly tested with Python 3.4.2 only.

### CODE REVIEW

**Comment by peterbe** [comment]
Does this still work in python 2? Don't you need a `from __future__ import print_function`?

**Comment by peterbe** [comment]
I think we need a test.

**Comment by scop** [comment]
print() should work with python 2 without any additional changes.

<pre>
$ python2 -c "print('hello')"
hello
</pre>

Tests obviously wouldn't hurt but as said, I've only tested ("manually") with 3.4.2 except for setup.py which I did test with 2.7.10. I don't plan to test with < 3.4.2 any more than that.

**Comment by peterbe** [comment]
Ok. I have a patch almost ready that adds tests so this project including travis. I'll try to finish it next week.

**Comment by peterbe** [comment]
Superseded by https://github.com/peterbe/django-html-validator/pull/10

**Pull request closed without merging**
